name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: recipe-finder-frontend
        run: npm install

      - name: Run lint
        working-directory: recipe-finder-frontend
        run: npm run lint

      - name: Build frontend
        working-directory: recipe-finder-frontend
        run: npm run build
